# Generated by Django 3.2 on 2021-04-13 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Types',
            new_name='Type',
        ),
    ]
