# Generated by Django 3.2 on 2021-04-13 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0003_manga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='chapter',
            field=models.IntegerField(verbose_name='Chapter'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='pages',
            field=models.IntegerField(help_text='Enter an integer representing number of pages', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(400)], verbose_name='Pages'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='plot',
            field=models.TextField(null=True, verbose_name='Plot'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='release_date',
            field=models.DateField(help_text='Please enter the release date of curent chapter', null=True, verbose_name='Release date'),
        ),
    ]
