# Generated by Django 3.2 on 2021-04-13 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0004_auto_20210413_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='rating',
            field=models.FloatField(default=5, help_text='Range 1-10 (10 is best, 1 is worst)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Rating'),
        ),
    ]
