# Generated by Django 3.2 on 2021-04-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0005_alter_manga_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('SHONEN', 'Shonen'), ('SHOJO', 'Shojo'), ('SEISEN', 'Seinen'), ('JOSEI', 'Josei'), ('KODOMOMUKE', 'Kodomomuke')], default='SHOJO', max_length=10, verbose_name='Type name'),
        ),
    ]
