# Generated by Django 3.2 on 2021-04-13 19:25

from django.db import migrations, models
import django.db.models.deletion
import manga.models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0006_alter_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(null=True, upload_to=manga.models.attachment_path, verbose_name='File')),
                ('type', models.CharField(choices=[('Poster', 'Poster'), ('Opening', 'Opening'), ('text', 'Text'), ('video', 'Video'), ('other', 'Other'), ('Manga', 'Manga')], default='Poster', help_text='Select allowed attachment type', max_length=7, verbose_name='Attachment type')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.manga')),
            ],
        ),
    ]
