# Generated by Django 3.1.7 on 2021-06-16 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0009_auto_20210516_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['name'], 'verbose_name': 'Type', 'verbose_name_plural': 'Types'},
        ),
    ]
